<a href="https://colab.research.google.com/github/GaborVxxx/ml_notes/blob/main/L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lest give it a go

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.5.1+cu121


# Intro to Tensors


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[7, 8, 6], [9, 10, 9], [6, 6, 6]]])
TENSOR

tensor([[[ 7,  8,  6],
         [ 9, 10,  9],
         [ 6,  6,  6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random **tesnsors**

This a starting point for displaying the data, later on we change it to better represent the correct data.

`Start random -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Creata the initial random tensor

# MATRIX (2D)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2401, 0.2829, 0.0103, 0.7141],
        [0.7042, 0.0801, 0.9980, 0.4036],
        [0.6492, 0.6033, 0.7118, 0.9439]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Creata the initial random tensor

# TENSOR (3D)

random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.8112, 0.4610, 0.8635, 0.3698],
         [0.5464, 0.7516, 0.9669, 0.6852],
         [0.6223, 0.3781, 0.2727, 0.1415]]])

In [ ]:
random_tensor.ndim

3

# Create a new tensor with a shape of an image

In [ ]:
# Image is 224 * 224 pixel and 3 color chanel

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones


In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Crateing a range of tensors and tensors-like

In [ ]:
# Use torch.arange()/range()

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create a tensors like (replicate a shape)

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

Note: There are 3 main point where we can run in to errors.


*   Tensor not right datatype
*   Tensor not right sahpe
*   Tensor not on the right device



In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # common float32 = single precision and 16 = half precision 64 = double precion
                               device=None, # default is "cpu" options like: "cuda", the point is keep this consistence where the tensor is in memory
                               requires_grad=False # to track the gradiant changes ...
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Convert the 32 bit to 16 bit (half)

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Tensor datatypes check method

Note: There are 3 main point where we can run in to errors.


*   Tensor not right datatype <-- tensor.dtype
*   Tensor not right sahpe <-- tensor.shape || size()
*   Tensor not on the right device <-- tensor.device

# Manipulate Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Devision
* matrix multiplication

In [ ]:
# Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply

tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substact

tensor - 1

tensor([0, 1, 2])

# There are build in functionns for this in PyTorch



*   torch.add()
*   torch.mul()
... etc



# Matrix multiplication

Two ways to perform multiplication in neural networks

1. Element-wise
2. Matrix multiplication (dot product)

ref: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication symbol -> @ OR torch.matmul()
torch.matmul(tensor, tensor)
tensor @ tensor

tensor(14)

There are two main rules for performing matrix multiplication.

1. The **inner dimensions** must match: more like **inner match outher**
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

`(2, 3) @ (3, 2)` -> [[1, 2, 3], [4, 5, 6]] * [[1, 2], [3, 4], [5, 6]]

2. The resulting matrix has the shape of the **outher dimensions**

`(2, 3) @ (3, 2)` -> shape of (2, 2) -> [[22, 28], [49, 64]]



# Most common error in deep learning is: **shape error**



In [ ]:
# Shape for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # || matmul || @

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# We can fix it by transposing one of the matrix to make the inner dimention match AKA turning the grid

print(tensor_B)
print(tensor_B.T)

torch.mm(tensor_A, tensor_B.T) # || matmul || @

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor Aggregation

Finding the Min, Max, Mean and Sum of Tensors

In [ ]:
# Create a tensor

x = torch.arange(0, 100, 10)
print(x)
print(x.dtype) # This will lead to problem when try to find mean

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# The data type error on mean AKA this is becous the mean() take floating as arg not int
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# Find the mean
print(x.dtype) # This will lead to problem when try to find mean
print(x.type(torch.float32)) # So we change the elements in the array to floating point
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # in order to work with it we need to change the tyep to floatingpoint from long int

torch.int64
tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])


(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Finding the positional min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
# Find the positional max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

# Reshaping, Viewing, Stacking, Squeezing, Unsqueezing and Permuting tensors

* Resaping - reshape an input tensor to a defined shape note: the resahpe hase to be comatable with the size
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - remove all `1` dimentions from a tensor
* Unsqueezing - add a `1` dimention to a target tensor
* Permuting - return a view of the input with dimentions permuted (swapped) in a certain way

In [ ]:
# Create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimention (Reshape) we can manipulate the shape based on how we rearange the number of elements.

x_reshape = x.reshape(3, 3)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view This is shate the same memory space just view it in different way

z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Changing z changes x (because a view of a tensor share the same memory) its like modification in place

z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
# Stack tensors on top of each other

x_stacked = torch.vstack([x, x, x, x])
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
# Stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
# Stack tensors horizontaly

x_stacked = torch.hstack([x, x, x, x])
x_stacked, x_stacked.shape

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9., 5., 2., 3., 5., 5., 6., 5., 8., 9.,
         5., 2., 3., 5., 5., 6., 5., 8., 9., 5., 2., 3., 5., 5., 6., 5., 8., 9.]),
 torch.Size([36]))

In [ ]:
# Satack experiment
q = torch.randn(1, 3, 3)
q

tensor([[[ 0.7225,  0.7714,  1.3631],
         [-0.3822,  0.6022,  0.2380],
         [-3.0537, -0.5929,  0.2725]]])

In [ ]:
torch.stack((q, q))

tensor([[[[ 0.7225,  0.7714,  1.3631],
          [-0.3822,  0.6022,  0.2380],
          [-3.0537, -0.5929,  0.2725]]],


        [[[ 0.7225,  0.7714,  1.3631],
          [-0.3822,  0.6022,  0.2380],
          [-3.0537, -0.5929,  0.2725]]]])

In [ ]:
torch.stack((q, q)).size()

torch.Size([2, 1, 3, 3])

In [ ]:
torch.stack((q, q), dim=3)

tensor([[[[ 0.7225,  0.7225],
          [ 0.7714,  0.7714],
          [ 1.3631,  1.3631]],

         [[-0.3822, -0.3822],
          [ 0.6022,  0.6022],
          [ 0.2380,  0.2380]],

         [[-3.0537, -3.0537],
          [-0.5929, -0.5929],
          [ 0.2725,  0.2725]]]])

In [ ]:
# Squeeze NOTE: like an un wrapper, remove the nesting of lvl 1 from a nested array

x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())
y = torch.squeeze(x, (1, 2, 3))
print(y.size())


torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 2, 2])


In [ ]:
# Unsqueeze NOTE: like a wrapper add an extra layer of nesting to an array ay dimention

x = torch.zeros(2, 2)
print(x.size())
y = torch.unsqueeze(x, 0)
print(y.size())
y = torch.unsqueeze(x, 1)
y
print(y.size())


torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([2, 1, 2])


In [ ]:
# Permute: rearanges tensor values in a specifed order re suffle the dimentions
x = torch.randn(2, 3, 5)
x.size()
torch.Size([2, 3, 5])
torch.permute(x, (2, 0, 1)).size()
torch.Size([5, 2, 3])



torch.Size([5, 2, 3])

In [ ]:
p = torch.randn(2, 3, 5)
p

tensor([[[ 0.4099, -1.5235, -3.1538,  0.4151, -0.6722],
         [-1.3320, -2.2945, -2.1761,  0.3197,  0.5965],
         [ 0.1491,  0.2053,  0.0232,  0.8306, -0.1889]],

        [[-0.2055, -0.6419, -0.2566, -0.6358, -1.0232],
         [-0.1738, -0.7887, -1.1517, -0.9890, -0.4291],
         [-0.1072,  0.2371, -0.9964, -1.1800,  1.2448]]])

In [ ]:
w = p.permute(1, 0, 2) # 3, 2, 5
w

tensor([[[ 0.4099, -1.5235, -3.1538,  0.4151, -0.6722],
         [-0.2055, -0.6419, -0.2566, -0.6358, -1.0232]],

        [[-1.3320, -2.2945, -2.1761,  0.3197,  0.5965],
         [-0.1738, -0.7887, -1.1517, -0.9890, -0.4291]],

        [[ 0.1491,  0.2053,  0.0232,  0.8306, -0.1889],
         [-0.1072,  0.2371, -0.9964, -1.1800,  1.2448]]])

# Indexing array/tensors

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create atensor

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on first item

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index the dim=1

x[0][0]

tensor([1, 2, 3])

In [ ]:
# Index in to the lat dimention

x[0][0][0]

tensor(1)

In [ ]:
# Can use ":" to select a target dimention

# 1 ":" give me the horizontal row
# 2 ":" give me the vertical row

x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors and NumPy

Numpy is a popular scientific Python numerical computing library
PyTotch has functions to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


NOTE: when we assigne a numpy array to a tensor its a copy! The tensor is not referencing the array, if we change the numpy array the tensor in not refelcting the cahnge.

NOTE: when we go from tensor to numpy array the numpy array enherit the data type of the tensor AKA -> float32


In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# NOTE: the data type is different!!!!!!!!!!!

z = torch.arange(1.0, 8.0)
z.dtype, array.dtype

(torch.float32, dtype('float64'))

In [ ]:
# So to be consistante between numpy and tensor we need to transform the data type to be float 32 when transforming a numpy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype


(dtype('float64'), torch.float32)

In [ ]:
# Tensor to NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Random seeding

Make the random reproducable by seting up a seed that produce the same random numbers.

In [ ]:
# Create two random tensor, but seed it and make it repruducable

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyThorc objects on GPU's to be faster

* 1 - use colub as it provide GPU
* 2 - use your own
* 3 - use cloud platform like GCP, AWS ...

In [ ]:
# Check PyThorc access to GPU

torch.cuda.is_available()

False