<a href="https://colab.research.google.com/github/GaborVxxx/ml_notes/blob/main/L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lest give it a go

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.5.1+cu121


# Intro to Tensors


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[7, 8, 6], [9, 10, 9], [6, 6, 6]]])
TENSOR

tensor([[[ 7,  8,  6],
         [ 9, 10,  9],
         [ 6,  6,  6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random **tesnsors**

This a starting point for displaying the data, later on we change it to better represent the correct data.

`Start random -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Creata the initial random tensor

# MATRIX (2D)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2886, 0.8051, 0.9252, 0.9369],
        [0.7046, 0.7731, 0.9036, 0.3963],
        [0.2535, 0.8286, 0.5800, 0.4397]])

In [16]:
random_tensor.ndim

2

In [17]:
# Creata the initial random tensor

# TENSOR (3D)

random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.5764, 0.5118, 0.1843, 0.1886],
         [0.8339, 0.6234, 0.6278, 0.8483],
         [0.3176, 0.5088, 0.8429, 0.9707]]])

In [18]:
random_tensor.ndim

3

# Create a new tensor with a shape of an image

In [19]:
# Image is 224 * 224 pixel and 3 color chanel

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones


In [20]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
# Create a tensor of all ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Crateing a range of tensors and tensors-like

In [24]:
# Use torch.arange()/range()

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Create a tensors like (replicate a shape)

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

Note: There are 3 main point where we can run in to errors.


*   Tensor not right datatype
*   Tensor not right sahpe
*   Tensor not on the right device



In [26]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # common float32 = single precision and 16 = half precision 64 = double precion
                               device=None, # default is "cpu" options like: "cuda", the point is keep this consistence where the tensor is in memory
                               requires_grad=False # to track the gradiant changes ...
                               )
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
# Convert the 32 bit to 16 bit (half)

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Tensor datatypes check method

Note: There are 3 main point where we can run in to errors.


*   Tensor not right datatype <-- tensor.dtype
*   Tensor not right sahpe <-- tensor.shape || size()
*   Tensor not on the right device <-- tensor.device

# Manipulate Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Devision
* matrix multiplication

In [29]:
# Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply

tensor * 10

tensor([10, 20, 30])

In [31]:
# Substact

tensor - 1

tensor([0, 1, 2])

# There are build in functionns for this in PyTorch



*   torch.add()
*   torch.mul()
... etc



# Matrix multiplication

Two ways to perform multiplication in neural networks

1. Element-wise
2. Matrix multiplication (dot product)

ref: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [32]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# Matrix multiplication symbol -> @ OR torch.matmul()
torch.matmul(tensor, tensor)
tensor @ tensor

tensor(14)

There are two main rules for performing matrix multiplication.

1. The **inner dimensions** must match: more like **inner match outher**
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

`(2, 3) @ (3, 2)` -> [[1, 2, 3], [4, 5, 6]] * [[1, 2], [3, 4], [5, 6]]

2. The resulting matrix has the shape of the **outher dimensions**

`(2, 3) @ (3, 2)` -> shape of (2, 2) -> [[22, 28], [49, 64]]



# Most common error in deep learning is: **shape error**



In [34]:
# Shape for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # || matmul || @

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [35]:
# We can fix it by transposing one of the matrix to make the inner dimention match AKA turning the grid

print(tensor_B)
print(tensor_B.T)

torch.mm(tensor_A, tensor_B.T) # || matmul || @

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor Aggregation

Finding the Min, Max, Mean and Sum of Tensors

In [36]:
# Create a tensor

x = torch.arange(0, 100, 10)
print(x)
print(x.dtype) # This will lead to problem when try to find mean

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [37]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [38]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [39]:
# The data type error on mean AKA this is becous the mean() take floating as arg not int
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [40]:
# Find the mean
print(x.dtype) # This will lead to problem when try to find mean
print(x.type(torch.float32)) # So we change the elements in the array to floating point
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # in order to work with it we need to change the tyep to floatingpoint from long int

torch.int64
tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])


(tensor(45.), tensor(45.))

In [41]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [42]:
# Finding the positional min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [43]:
# Find the positional max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

# Reshaping, Viewing, Stacking, Squeezing, Unsqueezing and Permuting tensors

* Resaping - reshape an input tensor to a defined shape note: the resahpe hase to be comatable with the size
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - remove all `1` dimentions from a tensor
* Unsqueezing - add a `1` dimention to a target tensor
* Permuting - return a view of the input with dimentions permuted (swapped) in a certain way

In [44]:
# Create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add an extra dimention (Reshape) we can manipulate the shape based on how we rearange the number of elements.

x_reshape = x.reshape(3, 3)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [46]:
# Change the view This is shate the same memory space just view it in different way

z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [47]:
# Changing z changes x (because a view of a tensor share the same memory) its like modification in place

z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [48]:
# Stack tensors on top of each other

x_stacked = torch.vstack([x, x, x, x])
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.]]),
 torch.Size([4, 9]))

In [49]:
# Stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.],
         [5., 2., 3., 5., 5., 6., 5., 8., 9.]]),
 torch.Size([4, 9]))

In [50]:
# Stack tensors horizontaly

x_stacked = torch.hstack([x, x, x, x])
x_stacked, x_stacked.shape

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9., 5., 2., 3., 5., 5., 6., 5., 8., 9.,
         5., 2., 3., 5., 5., 6., 5., 8., 9., 5., 2., 3., 5., 5., 6., 5., 8., 9.]),
 torch.Size([36]))

In [51]:
# Satack experiment
q = torch.randn(1, 3, 3)
q

tensor([[[-0.0435, -0.9802,  1.0306],
         [-0.2352, -0.7521, -0.2447],
         [-0.1182,  1.6069,  0.5561]]])

In [52]:
torch.stack((q, q))

tensor([[[[-0.0435, -0.9802,  1.0306],
          [-0.2352, -0.7521, -0.2447],
          [-0.1182,  1.6069,  0.5561]]],


        [[[-0.0435, -0.9802,  1.0306],
          [-0.2352, -0.7521, -0.2447],
          [-0.1182,  1.6069,  0.5561]]]])

In [53]:
torch.stack((q, q)).size()

torch.Size([2, 1, 3, 3])

In [54]:
torch.stack((q, q), dim=3)

tensor([[[[-0.0435, -0.0435],
          [-0.9802, -0.9802],
          [ 1.0306,  1.0306]],

         [[-0.2352, -0.2352],
          [-0.7521, -0.7521],
          [-0.2447, -0.2447]],

         [[-0.1182, -0.1182],
          [ 1.6069,  1.6069],
          [ 0.5561,  0.5561]]]])

In [55]:
# Squeeze NOTE: like an un wrapper, remove the nesting of lvl 1 from a nested array

x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())
y = torch.squeeze(x, (1, 2, 3))
print(y.size())


torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 2, 2])


In [56]:
# Unsqueeze NOTE: like a wrapper add an extra layer of nesting to an array ay dimention

x = torch.zeros(2, 2)
print(x.size())
y = torch.unsqueeze(x, 0)
print(y.size())
y = torch.unsqueeze(x, 1)
y
print(y.size())


torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([2, 1, 2])


In [57]:
# Permute: rearanges tensor values in a specifed order re suffle the dimentions
x = torch.randn(2, 3, 5)
x.size()
torch.Size([2, 3, 5])
torch.permute(x, (2, 0, 1)).size()
torch.Size([5, 2, 3])



torch.Size([5, 2, 3])

In [58]:
p = torch.randn(2, 3, 5)
p

tensor([[[ 1.1876,  0.6164,  1.4547,  0.4888,  0.3526],
         [-1.7473,  0.6400, -0.4248,  1.3388,  0.2180],
         [ 0.6585, -2.6309, -0.6758,  1.0888,  0.1241]],

        [[-0.6531,  1.4013,  1.3400,  0.8724, -0.5964],
         [ 0.4843,  0.2726, -0.5159, -0.9512, -0.0812],
         [-0.1184,  0.4930,  1.4130,  0.3677,  0.8620]]])

In [59]:
w = p.permute(1, 0, 2) # 3, 2, 5
w

tensor([[[ 1.1876,  0.6164,  1.4547,  0.4888,  0.3526],
         [-0.6531,  1.4013,  1.3400,  0.8724, -0.5964]],

        [[-1.7473,  0.6400, -0.4248,  1.3388,  0.2180],
         [ 0.4843,  0.2726, -0.5159, -0.9512, -0.0812]],

        [[ 0.6585, -2.6309, -0.6758,  1.0888,  0.1241],
         [-0.1184,  0.4930,  1.4130,  0.3677,  0.8620]]])

# Indexing array/tensors

Indexing with PyTorch is similar to indexing with NumPy

In [60]:
# Create atensor

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
# Lets index on first item

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
# Index the dim=1

x[0][0]

tensor([1, 2, 3])

In [63]:
# Index in to the lat dimention

x[0][0][0]

tensor(1)

In [64]:
# Can use ":" to select a target dimention

# 1 ":" give me the horizontal row
# 2 ":" give me the vertical row

x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors and NumPy

Numpy is a popular scientific Python numerical computing library
PyTotch has functions to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


NOTE: when we assigne a numpy array to a tensor its a copy! The tensor is not referencing the array, if we change the numpy array the tensor in not refelcting the cahnge.

NOTE: when we go from tensor to numpy array the numpy array enherit the data type of the tensor AKA -> float32


In [65]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# NOTE: the data type is different!!!!!!!!!!!

z = torch.arange(1.0, 8.0)
z.dtype, array.dtype

(torch.float32, dtype('float64'))

In [67]:
# So to be consistante between numpy and tensor we need to transform the data type to be float 32 when transforming a numpy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype


(dtype('float64'), torch.float32)

In [68]:
# Tensor to NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Random seeding

Make the random reproducable by seting up a seed that produce the same random numbers.

In [69]:
# Create two random tensor, but seed it and make it repruducable

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyThorc objects on GPU's to be faster

* 1 - use colub as it provide GPU
* 2 - use your own
* 3 - use cloud platform like GCP, AWS ...

REF: https://pytorch.org/docs/stable/notes/cuda

In [70]:
# Check PyThorc access to GPU

torch.cuda.is_available()

True

In [71]:
# Set up device agnostic code AKA use what ever is available

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [72]:
# Count number of devices

torch.cuda.device_count()

1

# Putting tensors (and models) on GPU

Why? For fasted compiutation.

In [73]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [74]:
# Move tesor to GPU (if available)
tensor_on_gpu = tensor.to(device) # <-- shift the tensor we created to GPU
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving tensor back to CPU

Note: If we use NumPy operation, NumPy only work on CPU.

In [77]:
# Move back to CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy().astype(np.float32)
tensor_back_on_cpu, tensor_back_on_cpu.dtype

(array([1., 2., 3.], dtype=float32), dtype('float32'))